extends Node

var chart = [
	["knock",null,null,null," knock",null,null,null,false],
	["who's",null,null,null," there?",null,null,null,false],
	["it's"," me,",null,null," Nan","ya!",null,null,false],
	["Nan","ya?",null,null," which"," one?",null,null,false],
	["Nan","ya",null,null,null," bus","iness!",null,true],
	["that's ","a",null,null,null," good"," one!",null,false],
	["thank",null," you",null," dear",null," friend",null,false],
	["...for",null," a",null," rook",null,"ie",null,true],
	["oh,",null,null,null," you... ",null,null,null,false],
	["ha",null,null,null,"ha!",null,null,null,false],
	["did"," you"," see"," the"," three"," blind"," mice?",null,false],
	["have","n't"," seen"," one!"," hard","ly"," thrice!",null,false],
	["they"," did","n't"," see"," us"," eith","er.",null,true],
	["some"," would"," say"," they"," are"," luck","y",null,false],
	["what"," do "," you"," mean"," by",null," that?",null,false],
	["i'm"," say","ing"," you're"," a",null," clown!",null,true],
	["did"," you"," hear?",null," tra","ge","dy!",null,false],
	["oh"," my"," gosh!",null," re","a","lly?",null,false],
	["boil","ing"," wa","ter"," died"," last"," week...",null,false],
	["that's"," sad"," to"," hear."," they'll"," be"," mist!",null,true],
	["i"," have"," got"," good"," news"," though!",null,null,false],
	["some","thing"," good?"," let"," me"," hear!",null,null,false],
	["my"," drumm","er"," friend's"," hav","ing"," kids!",null,false],
	["oh?"," what"," will"," they"," name"," them"," then?",null,false],
	["An","na"," one.",null," An","na"," two.",null,true],
	["An","na"," one?",null," two?"," three?"," four?",null,false],
	["on","ly"," two.",null,null," they're"," twins.",null,false],
	["they'd"," call"," 'em",null,null," kick"," snare!",null,false],
	["or"," what"," a","bout"," hi"," and"," hat?",null,true],
	["you're"," on","to"," some","thing"," with"," that.",null,false],
	["i'd"," like",null," to"," learn"," to"," cook.",null,false],
	["i"," could",null," teach"," a"," ni","bble!",null,false],
	["can",null," we",null," make"," egg"," roll?",null,false],
	["ea",null,"sy!",null," just"," push"," it!",null,true],
	[null,null,null,null,null,null,null,null,false],
	[null,null,null,null,null,null,null,null,false],
]
